services:
  web:
    image: nginx:mainline-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./templates:/etc/nginx/templates:ro
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    networks:
      - backend-network

networks:
  backend-network:
    name: caddy-backend-network
    external: true
